services:
  postgresql:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: temporal
    ports: [ "5432:5432" ]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  temporal:
    image: temporalio/auto-setup:latest
    ports: [ "7233:7233" ]
    environment:
      DB: postgresql
      POSTGRES_USER: postgres
      POSTGRES_PWD: postgres
      POSTGRES_SEEDS: postgresql
    depends_on:
      postgresql:
        condition: service_healthy

  temporal-web:
    image: temporalio/web:latest
    ports: [ "8233:8080" ]
    environment:
      TEMPORAL_ADDRESS: temporal:7233
    depends_on: [ temporal ]