version: "3.8"
services:
  postgresql:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: temporal
    ports: [ "5432:5432" ]

  temporal:
    image: temporalio/auto-setup:1.25.0
    ports: [ "7233:7233" ]
    environment:
      DB: postgresql
      POSTGRES_PWD: postgres
      POSTGRES_USER: postgres
      POSTGRES_SEEDS: postgresql
    depends_on: [ postgresql ]

  temporal-web:
    image: temporalio/web:2.24.0
    ports: [ "8233:8080" ]
    environment:
      TEMPORAL_ADDRESS: temporal:7233